xrif: First Differencing
First Differencing
Top-level interface » Encoding & Decoding » Differencing
The first differencing method uses the first frame as the reference for all subsequent frames.
Functions
xrif_error_t xrif_difference_first (xrif_t handle)
Difference the images using the first image as a reference.
xrif_error_t xrif_difference_first_sint16 (xrif_t handle)
Difference all images with respect to the first image, for signed 16-bit integer data type.
xrif_error_t xrif_difference_first_sint32 (xrif_t handle)
Difference all images with respect to the first image, for signed 32-bit integer data type.
xrif_error_t xrif_difference_first_sint64 (xrif_t handle)
Difference all images with respect to the first image, for signed 64-bit integer data type.
xrif_error_t xrif_undifference_first (xrif_t handle)
Undifference the images using the first image as a reference.
xrif_error_t xrif_undifference_first_sint16 (xrif_t handle)
Reverse the differencing operation, w.r.t. the first image, for signed 16-bit integer data type.
xrif_error_t xrif_undifference_first_sint32 (xrif_t handle)
Reverse the differencing operation, w.r.t. the first image, for signed 32-bit integer data type.
xrif_error_t xrif_undifference_first_sint64 (xrif_t handle)
Reverse the differencing operation, w.r.t. the first image, for signed 64-bit integer data type.
Function Documentation
xrif_difference_first()
xrif_error_t xrif_difference_first (xrif_t handle)
Difference the images using the first image as a reference.
This function calls the type specific difference function for the type specified by handle->type_code.
Returns
XRIF_ERROR_NULLPTR if the handle is NULL
XRIF_ERROR_NOTIMPL if differencing is not implemented for the type specified in xrif_handle::type_code
other error codes from the differencing functions
XRIF_NOERROR on success
Test:
Verify first differencing for int16_t [test doc]
Verify first differencing for uint16_t [test doc]
Verify first differencing for int32_t [test doc]
Verify first differencing for uint32_t [test doc]
Verify first differencing for int64_t [test doc]
Verify first differencing for uint64_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1282 of file xrif.c.
References xrif_handle::type_code, xrif_difference_first_sint16(), xrif_difference_first_sint32(), xrif_difference_first_sint64(), XRIF_ERROR_NOTIMPL, XRIF_ERROR_NULLPTR, XRIF_ERROR_PRINT, XRIF_TYPECODE_INT16, XRIF_TYPECODE_INT32, XRIF_TYPECODE_INT64, XRIF_TYPECODE_UINT16, XRIF_TYPECODE_UINT32, and XRIF_TYPECODE_UINT64.
xrif_difference_first_sint16()
xrif_error_t xrif_difference_first_sint16 (xrif_t handle)
Difference all images with respect to the first image, for signed 16-bit integer data type.
Returns
XRIF_NOERROR on success.
Test:
Verify first differencing for int16_t [test doc]
Verify first differencing for uint16_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1309 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_difference_first().
xrif_difference_first_sint32()
xrif_error_t xrif_difference_first_sint32 (xrif_t handle)
Difference all images with respect to the first image, for signed 32-bit integer data type.
Returns
XRIF_NOERROR on success.
Test:
Verify first differencing for int32_t [test doc]
Verify first differencing for uint32_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1354 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_difference_first().
xrif_difference_first_sint64()
xrif_error_t xrif_difference_first_sint64 (xrif_t handle)
Difference all images with respect to the first image, for signed 64-bit integer data type.
Returns
XRIF_NOERROR on success.
Test:
Verify first differencing for int64_t [test doc]
Verify first differencing for uint64_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1379 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_difference_first().
xrif_undifference_first()
xrif_error_t xrif_undifference_first (xrif_t handle)
Undifference the images using the first image as a reference.
This function calls the type specific undifference function for the type specified by handle->type_code.
Returns
XRIF_ERROR_NULLPTR if the handle is NULL
XRIF_ERROR_NOTIMPL if undifferencing is not implemented for the type specified in xrif_handle::type_code
XRIF_ERROR codes from the undifferencing functions
XRIF_NOERROR on success
Test:
Verify first differencing for int16_t [test doc]
Verify first differencing for uint16_t [test doc]
Verify first differencing for int32_t [test doc]
Verify first differencing for uint32_t [test doc]
Verify first differencing for int64_t [test doc]
Verify first differencing for uint64_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1689 of file xrif.c.
References xrif_handle::type_code, XRIF_ERROR_NULLPTR, XRIF_ERROR_PRINT, XRIF_TYPECODE_INT16, XRIF_TYPECODE_INT32, XRIF_TYPECODE_INT64, XRIF_TYPECODE_UINT16, XRIF_TYPECODE_UINT32, XRIF_TYPECODE_UINT64, xrif_undifference_first_sint16(), xrif_undifference_first_sint32(), and xrif_undifference_first_sint64().
xrif_undifference_first_sint16()
xrif_error_t xrif_undifference_first_sint16 (xrif_t handle)
Reverse the differencing operation, w.r.t. the first image, for signed 16-bit integer data type.
Note that this is currently used for unsigned 16-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
Test:
Verify first differencing for int16_t [test doc]
Verify first differencing for uint16_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1717 of file xrif.c.
References xrif_handle::depth, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_undifference_first().
xrif_undifference_first_sint32()
xrif_error_t xrif_undifference_first_sint32 (xrif_t handle)
Reverse the differencing operation, w.r.t. the first image, for signed 32-bit integer data type.
Note that this is currently used for unsigned 32-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
Test:
Verify first differencing for int32_t [test doc]
Verify first differencing for uint32_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1745 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_undifference_first().
xrif_undifference_first_sint64()
xrif_error_t xrif_undifference_first_sint64 (xrif_t handle)
Reverse the differencing operation, w.r.t. the first image, for signed 64-bit integer data type.
Note that this is currently used for unsigned 64-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
Test:
Verify first differencing for int64_t [test doc]
Verify first differencing for uint64_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1771 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_undifference_first().