xrif: Pixel Differencing
Pixel Differencing
Top-level interface » Encoding & Decoding » Differencing
The pixel differencing method uses the previous pixel as the reference.
Functions
xrif_error_t xrif_difference_pixel (xrif_t handle)
Difference the images using the first pixel of each frame as a reference.
xrif_error_t xrif_difference_pixel_sint16 (xrif_t handle)
Difference each image with respect to its first pixel, for signed 16-bit integer data type.
xrif_error_t xrif_difference_pixel_sint32 (xrif_t handle)
Difference each image with respect to its first pixel, for signed 32-bit integer data type.
xrif_error_t xrif_difference_pixel_sint64 (xrif_t handle)
Difference each image with respect to its first pixel, for signed 64-bit integer data type.
xrif_error_t xrif_undifference_pixel (xrif_t handle)
Undifference the images using the first pixel of each as a reference.
xrif_error_t xrif_undifference_pixel_sint16 (xrif_t handle)
Reverse the differencing operation on each image with respect to its first pixel, for signed 16-bit integer data type.
xrif_error_t xrif_undifference_pixel_sint32 (xrif_t handle)
Reverse the differencing operation on each image with respect to its first pixel, for signed 32-bit integer data type.
xrif_error_t xrif_undifference_pixel_sint64 (xrif_t handle)
Reverse the differencing operation on each image with respect to its first pixel, for signed 64-bit integer data type.
Function Documentation
xrif_difference_pixel()
xrif_error_t xrif_difference_pixel (xrif_t handle)
Difference the images using the first pixel of each frame as a reference.
This function calls the type specific difference function for the type specified by handle->type_code.
Returns
XRIF_ERROR_NULLPTR if the handle is NULL
XRIF_ERROR_NOTIMPL if differencing is not implemented for the type specified in xrif_handle::type_code
other error codes from the differencing functions
XRIF_NOERROR on success
Test:
Verify pixel differencing for int16_t [test doc]
Verify pixel differencing for uint16_t [test doc]
Verify pixel differencing for int32_t [test doc]
Verify pixel differencing for uint32_t [test doc]
Verify pixel differencing for int64_t [test doc]
Verify pixel differencing for uint64_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1405 of file xrif.c.
References xrif_handle::type_code, xrif_difference_pixel_sint16(), xrif_difference_pixel_sint32(), xrif_difference_pixel_sint64(), XRIF_ERROR_NOTIMPL, XRIF_ERROR_NULLPTR, XRIF_ERROR_PRINT, XRIF_TYPECODE_INT16, XRIF_TYPECODE_INT32, XRIF_TYPECODE_INT64, XRIF_TYPECODE_UINT16, XRIF_TYPECODE_UINT32, and XRIF_TYPECODE_UINT64.
xrif_difference_pixel_sint16()
xrif_error_t xrif_difference_pixel_sint16 (xrif_t handle)
Difference each image with respect to its first pixel, for signed 16-bit integer data type.
Note: This function is currently also used for unsigned 16-bit integers.
Returns
XRIF_NOERROR on success.
Test:
Verify pixel differencing for int16_t [test doc]
Verify pixel differencing for uint16_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1432 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_difference_pixel().
xrif_difference_pixel_sint32()
xrif_error_t xrif_difference_pixel_sint32 (xrif_t handle)
Difference each image with respect to its first pixel, for signed 32-bit integer data type.
Note: This function is currently also used for unsigned 32-bit integers.
Returns
XRIF_NOERROR on success.
Test:
Verify pixel differencing for int32_t [test doc]
Verify pixel differencing for uint32_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1469 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_difference_pixel().
xrif_difference_pixel_sint64()
xrif_error_t xrif_difference_pixel_sint64 (xrif_t handle)
Difference each image with respect to its first pixel, for signed 64-bit integer data type.
Note: This function is currently also used for unsigned 64-bit integers.
Returns
XRIF_NOERROR on success.
Test:
Verify pixel differencing for int64_t [test doc]
Verify pixel differencing for uint64_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1490 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_difference_pixel().
xrif_undifference_pixel()
xrif_error_t xrif_undifference_pixel (xrif_t handle)
Undifference the images using the first pixel of each as a reference.
This function calls the type specific undifference function for the type specified by handle->type_code.
Returns
XRIF_ERROR_NULLPTR if the handle is NULL
XRIF_ERROR_NOTIMPL if undifferencing is not implemented for the type specified in xrif_handle::type_code
XRIF_ERROR codes from the undifferencing functions
XRIF_NOERROR on success
Test:
Verify pixel differencing for int16_t [test doc]
Verify pixel differencing for uint16_t [test doc]
Verify pixel differencing for int32_t [test doc]
Verify pixel differencing for uint32_t [test doc]
Verify pixel differencing for int64_t [test doc]
Verify pixel differencing for uint64_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1799 of file xrif.c.
References xrif_handle::type_code, XRIF_ERROR_NULLPTR, XRIF_ERROR_PRINT, XRIF_TYPECODE_INT16, XRIF_TYPECODE_INT32, XRIF_TYPECODE_INT64, XRIF_TYPECODE_UINT16, XRIF_TYPECODE_UINT32, XRIF_TYPECODE_UINT64, xrif_undifference_pixel_sint16(), xrif_undifference_pixel_sint32(), and xrif_undifference_pixel_sint64().
xrif_undifference_pixel_sint16()
xrif_error_t xrif_undifference_pixel_sint16 (xrif_t handle)
Reverse the differencing operation on each image with respect to its first pixel, for signed 16-bit integer data type.
Note that this is currently used for unsigned 16-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
Test:
Verify pixel differencing for int16_t [test doc]
Verify pixel differencing for uint16_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1827 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_undifference_pixel().
xrif_undifference_pixel_sint32()
xrif_error_t xrif_undifference_pixel_sint32 (xrif_t handle)
Reverse the differencing operation on each image with respect to its first pixel, for signed 32-bit integer data type.
Note that this is currently used for unsigned 32-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
Test:
Verify pixel differencing for int32_t [test doc]
Verify pixel differencing for uint32_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1848 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_undifference_pixel().
xrif_undifference_pixel_sint64()
xrif_error_t xrif_undifference_pixel_sint64 (xrif_t handle)
Reverse the differencing operation on each image with respect to its first pixel, for signed 64-bit integer data type.
Note that this is currently used for unsigned 64-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
Test:
Verify pixel differencing for int64_t [test doc]
Verify pixel differencing for uint64_t [test doc]
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1869 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_undifference_pixel().