xrif: Performance Measurements
Performance Measurements
Top-level interface
Functions
double xrif_compression_ratio (xrif_t handle)
Calculate the compression ratio.
double xrif_encode_time (xrif_t handle)
Calculate the time in seconds taken to encode the data.
double xrif_encode_rate (xrif_t handle)
Calculate the encode rate in bytes/sec.
double xrif_difference_time (xrif_t handle)
Calculate the time in seconds taken to difference the data.
double xrif_difference_rate (xrif_t handle)
Calculate the differencing rate in bytes/sec.
double xrif_reorder_time (xrif_t handle)
Calculate the time in seconds taken to reorder the data.
double xrif_reorder_rate (xrif_t handle)
Calculate the reordering rate in bytes/sec.
double xrif_compress_time (xrif_t handle)
Calculate the time in seconds taken to compress the differenced and reordered data.
double xrif_compress_rate (xrif_t handle)
Calculate the compression rate in bytes/sec.
double xrif_decode_time (xrif_t handle)
Calculate the time in seconds taken to decode the data.
double xrif_decode_rate (xrif_t handle)
Calculate the decode rate in bytes/sec.
double xrif_undifference_time (xrif_t handle)
Calculate the time in seconds taken to undifference the data.
double xrif_undifference_rate (xrif_t handle)
Calculate the undifferencing rate in bytes/sec.
double xrif_unreorder_time (xrif_t handle)
Calculate the time in seconds taken to unreorder the data.
double xrif_unreorder_rate (xrif_t handle)
Calculate the unreordering rate in bytes/sec.
double xrif_decompress_time (xrif_t handle)
Calculate the time in seconds taken to decompress the differenced and reordered data.
double xrif_decompress_rate (xrif_t handle)
Calculate the decompression rate in bytes/sec.
Function Documentation
xrif_compress_rate()
double xrif_compress_rate (xrif_t handle)
Calculate the compression rate in bytes/sec.
Returns
the ratio of raw_size to xrif_compress_time
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2104 of file xrif.c.
References xrif_handle::raw_size, and xrif_compress_time().
xrif_compress_time()
double xrif_compress_time (xrif_t handle)
Calculate the time in seconds taken to compress the differenced and reordered data.
Returns
the difference in the timespecs marking the beginning of reordering and the end of compression
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2099 of file xrif.c.
References xrif_handle::ts_compress_done, xrif_handle::ts_compress_start, and xrif_ts_difference().
Referenced by xrif_compress_rate().
xrif_compression_ratio()
double xrif_compression_ratio (xrif_t handle)
Calculate the compression ratio.
Returns
the ratio of compressed_size to raw_size.
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2064 of file xrif.c.
References xrif_handle::compressed_size, and xrif_handle::raw_size.
xrif_decode_rate()
double xrif_decode_rate (xrif_t handle)
Calculate the decode rate in bytes/sec.
Returns
the ratio of raw_size to xrif_decode_time
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2116 of file xrif.c.
References xrif_handle::raw_size, and xrif_decode_time().
xrif_decode_time()
double xrif_decode_time (xrif_t handle)
Calculate the time in seconds taken to decode the data.
Returns
the difference in the timespecs marking the beginning of decompression and the end of undifferencing
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2111 of file xrif.c.
References xrif_handle::ts_decompress_start, xrif_handle::ts_undifference_done, and xrif_ts_difference().
Referenced by xrif_decode_rate().
xrif_decompress_rate()
double xrif_decompress_rate (xrif_t handle)
Calculate the decompression rate in bytes/sec.
Returns
the ratio of raw_size to xrif_decompress_time
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2146 of file xrif.c.
References xrif_handle::raw_size, and xrif_decompress_time().
xrif_decompress_time()
double xrif_decompress_time (xrif_t handle)
Calculate the time in seconds taken to decompress the differenced and reordered data.
Returns
the difference in the timespecs marking the decompression time
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2141 of file xrif.c.
References xrif_handle::ts_decompress_start, xrif_handle::ts_unreorder_start, and xrif_ts_difference().
Referenced by xrif_decompress_rate().
xrif_difference_rate()
double xrif_difference_rate (xrif_t handle)
Calculate the differencing rate in bytes/sec.
Returns
the ratio of raw_size to xrif_difference_time
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2084 of file xrif.c.
References xrif_handle::raw_size, and xrif_difference_time().
xrif_difference_time()
double xrif_difference_time (xrif_t handle)
Calculate the time in seconds taken to difference the data.
Returns
the difference in the timespecs marking the beginning of reordering and the beginning of differencing
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2079 of file xrif.c.
References xrif_handle::ts_difference_start, xrif_handle::ts_reorder_start, and xrif_ts_difference().
Referenced by xrif_difference_rate().
xrif_encode_rate()
double xrif_encode_rate (xrif_t handle)
Calculate the encode rate in bytes/sec.
Returns
the ratio of raw_size to xrif_encode_time
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2074 of file xrif.c.
References xrif_handle::raw_size, and xrif_encode_time().
xrif_encode_time()
double xrif_encode_time (xrif_t handle)
Calculate the time in seconds taken to encode the data.
Returns
the difference in the timespecs marking the beginning of differencing the end of compression
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2069 of file xrif.c.
References xrif_handle::ts_compress_done, xrif_handle::ts_difference_start, and xrif_ts_difference().
Referenced by xrif_encode_rate().
xrif_reorder_rate()
double xrif_reorder_rate (xrif_t handle)
Calculate the reordering rate in bytes/sec.
Returns
the ratio of raw_size to xrif_reorder_time
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2094 of file xrif.c.
References xrif_handle::raw_size, and xrif_reorder_time().
xrif_reorder_time()
double xrif_reorder_time (xrif_t handle)
Calculate the time in seconds taken to reorder the data.
Returns
the difference in the timespecs marking the beginning of compression and the beginning of reordering
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2089 of file xrif.c.
References xrif_handle::ts_compress_start, xrif_handle::ts_reorder_start, and xrif_ts_difference().
Referenced by xrif_reorder_rate().
xrif_undifference_rate()
double xrif_undifference_rate (xrif_t handle)
Calculate the undifferencing rate in bytes/sec.
Returns
the ratio of raw_size to xrif_undifference_time
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2126 of file xrif.c.
References xrif_handle::raw_size, and xrif_undifference_time().
xrif_undifference_time()
double xrif_undifference_time (xrif_t handle)
Calculate the time in seconds taken to undifference the data.
Returns
the difference in the timespecs marking the end of undifferencing and the end of unreodering
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2121 of file xrif.c.
References xrif_handle::ts_undifference_done, xrif_handle::ts_undifference_start, and xrif_ts_difference().
Referenced by xrif_undifference_rate().
xrif_unreorder_rate()
double xrif_unreorder_rate (xrif_t handle)
Calculate the unreordering rate in bytes/sec.
Returns
the ratio of raw_size to xrif_unreorder_time
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2136 of file xrif.c.
References xrif_handle::raw_size, and xrif_unreorder_time().
xrif_unreorder_time()
double xrif_unreorder_time (xrif_t handle)
Calculate the time in seconds taken to unreorder the data.
Returns
the difference in the timespecs marking the beginning of differencing and the end of decompression
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 2131 of file xrif.c.
References xrif_handle::ts_undifference_start, xrif_handle::ts_unreorder_start, and xrif_ts_difference().
Referenced by xrif_unreorder_rate().