xrif: Previous Differencing
Previous Differencing
The main xrif library interface » Encoding & Decoding » Differencing
The previous differencing method uses the previous frame as the reference.
Functions
xrif_error_t xrif_difference_previous (xrif_t handle)
Difference the images using the previous image as a reference.
xrif_error_t xrif_difference_previous_sint16 (xrif_t handle)
Difference all images with respect to previous image, for signed 16-bit integer data type.
xrif_error_t xrif_difference_previous_sint32 (xrif_t handle)
Difference all images with respect to previous image, for signed 32-bit integer data type.
xrif_error_t xrif_difference_previous_sint64 (xrif_t handle)
Difference all images with respect to previous image, for signed 64-bit data type.
xrif_error_t xrif_undifference_previous (xrif_t handle)
Undifference the images using the previous image as a reference.
xrif_error_t xrif_undifference_previous_sint16 (xrif_t handle)
Reverse the differencing operation, w.r.t. the previous image, for signed 16-bit integer data type.
xrif_error_t xrif_undifference_previous_sint32 (xrif_t handle)
Reverse the differencing operation, w.r.t. the previous image, for signed 32-bit integer data type.
xrif_error_t xrif_undifference_previous_sint64 (xrif_t handle)
Reverse the differencing operation, w.r.t. the previous image, for signed 64-bit integer data type.
Function Documentation
xrif_difference_previous()
xrif_error_t xrif_difference_previous (xrif_t handle)
Difference the images using the previous image as a reference.
This function calls the type specific difference function for the type specified by handle->type_code.
Returns
XRIF_ERROR_NULLPTR if the handle is NULL
XRIF_ERROR_NOTIMPL if differencing is not implemented for the type specified in xrif_handle::type_code
other error codes from the differencing functions
XRIF_NOERROR on success
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1085 of file xrif.c.
References xrif_handle::type_code, xrif_difference_previous_sint16(), xrif_difference_previous_sint32(), xrif_difference_previous_sint64(), XRIF_ERROR_NOTIMPL, XRIF_ERROR_NULLPTR, XRIF_ERROR_PRINT, XRIF_TYPECODE_INT16, XRIF_TYPECODE_INT32, XRIF_TYPECODE_INT64, XRIF_TYPECODE_UINT16, XRIF_TYPECODE_UINT32, and XRIF_TYPECODE_UINT64.
xrif_difference_previous_sint16()
xrif_error_t xrif_difference_previous_sint16 (xrif_t handle)
Difference all images with respect to previous image, for signed 16-bit integer data type.
Note that this is currently used for unsigned 16-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
XRIF_ERROR_XXXX on error, with the appropriate error code.
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1113 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_difference_previous().
xrif_difference_previous_sint32()
xrif_error_t xrif_difference_previous_sint32 (xrif_t handle)
Difference all images with respect to previous image, for signed 32-bit integer data type.
Note that this is currently used for unsigned 32-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
XRIF_ERROR_XXXXX on error, with the appropriate error code.
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1147 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_difference_previous().
xrif_difference_previous_sint64()
xrif_error_t xrif_difference_previous_sint64 (xrif_t handle)
Difference all images with respect to previous image, for signed 64-bit data type.
Note that this is currently used for unsigned 64-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
XRIF_ERROR_XXXXX on error, with the appropriate error code.
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1181 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_difference_previous().
xrif_undifference_previous()
xrif_error_t xrif_undifference_previous (xrif_t handle)
Undifference the images using the previous image as a reference.
This function calls the type specific undifference function for the type specified by handle->type_code.
Returns
XRIF_ERROR_NULLPTR if the handle is NULL
XRIF_ERROR_NOTIMPL if undifferencing is not implemented for the type specified in xrif_handle::type_code
XRIF_ERROR codes from the undifferencing functions
XRIF_NOERROR on success
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1359 of file xrif.c.
References xrif_handle::type_code, XRIF_ERROR_NULLPTR, XRIF_ERROR_PRINT, XRIF_TYPECODE_INT16, XRIF_TYPECODE_INT32, XRIF_TYPECODE_INT64, XRIF_TYPECODE_UINT16, XRIF_TYPECODE_UINT32, XRIF_TYPECODE_UINT64, xrif_undifference_previous_sint16(), xrif_undifference_previous_sint32(), and xrif_undifference_previous_sint64().
xrif_undifference_previous_sint16()
xrif_error_t xrif_undifference_previous_sint16 (xrif_t handle)
Reverse the differencing operation, w.r.t. the previous image, for signed 16-bit integer data type.
Note that this is currently used for unsigned 16-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
XRIF_ERROR on error, with the appropreate error code.
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1387 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_undifference_previous().
xrif_undifference_previous_sint32()
xrif_error_t xrif_undifference_previous_sint32 (xrif_t handle)
Reverse the differencing operation, w.r.t. the previous image, for signed 32-bit integer data type.
Note that this is currently used for unsigned 32-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
XRIF_ERROR_XXXXX on error, with the appropriate error code.
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1416 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_undifference_previous().
xrif_undifference_previous_sint64()
xrif_error_t xrif_undifference_previous_sint64 (xrif_t handle)
Reverse the differencing operation, w.r.t. the previous image, for signed 64-bit integer data type.
Note that this is currently used for unsigned 64-bits as well. This is likely suboptimal.
Returns
XRIF_NOERROR on success.
XRIF_ERROR_XXXXX on error, with the appropriate error code.
Parameters
[in,out] handle [in/out] the xrif handle
Definition at line 1445 of file xrif.c.
References xrif_handle::depth, xrif_handle::frames, xrif_handle::height, xrif_handle::raw_buffer, xrif_handle::width, and XRIF_NOERROR.
Referenced by xrif_undifference_previous().