xrif: /home/jrmales/Source/xrif/tests/xrif_test_difference_first_whitenoise.c File Reference
xrif_test_difference_first_whitenoise.c File Reference
Test the first differencing method with white noise.
Test the first differencing method with white noise.
Author
Jared R. Males (jared.nosp@m.male.nosp@m.s@gma.nosp@m.il.c.nosp@m.om)
Definition in file xrif_test_difference_first_whitenoise.c.
#include <check.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <limits.h>
#include "../src/xrif.h"
#include "randutils.h"
Macros
#define XRIF_TEST_TRIALS (2)
Functions
START_TEST (diff_first_int16_white)
START_TEST (diff_first_uint16_white)
START_TEST (diff_first_int32_white)
START_TEST (diff_first_uint32_white)
START_TEST (diff_first_int64_white)
START_TEST (diff_first_uint64_white)
Suite * whitenoise_suite (void)
int main (int argc, char **argv)
Variables
int test_trials
int ws [] = {2,4,8,21, 33, 47, 64}
int hs [] = {2,4,8,21, 33, 47, 64}
int ps [] = {1,2,4,5,27,63,64}
END_TEST
Function Documentation
START_TEST() [1/6]
START_TEST (diff_first_int16_white)
Verify first differencing for int16_t Verify that xrif difference/un-difference cycle using the first image works with white noise for int16_t.
Definition at line 117 of file xrif_test_difference_first_whitenoise.c.
References xrif_new(), and XRIF_NOERROR.
START_TEST() [2/6]
START_TEST (diff_first_int32_white)
Verify first differencing for int32_t Verify that xrif difference/un-difference cycle using the first image works with white noise for int32_t.
Definition at line 247 of file xrif_test_difference_first_whitenoise.c.
References xrif_new(), and XRIF_NOERROR.
START_TEST() [3/6]
START_TEST (diff_first_int64_white)
Verify first differencing for int64_t Verify that xrif difference/un-difference cycle using the first image works with white noise for int64_t.
Definition at line 377 of file xrif_test_difference_first_whitenoise.c.
References xrif_new(), and XRIF_NOERROR.
START_TEST() [4/6]
START_TEST (diff_first_uint16_white)
Verify first differencing for uint16_t Verify that xrif difference/un-difference cycle using the first image works with white noise for uint16_t.
Definition at line 182 of file xrif_test_difference_first_whitenoise.c.
References xrif_new(), and XRIF_NOERROR.
START_TEST() [5/6]
START_TEST (diff_first_uint32_white)
Verify first differencing for uint32_t Verify that xrif difference/un-difference cycle using the first image works with white noise for uint32_t.
Definition at line 312 of file xrif_test_difference_first_whitenoise.c.
References xrif_new(), and XRIF_NOERROR.
START_TEST() [6/6]
START_TEST (diff_first_uint64_white)
Verify first differencing for uint64_t Verify that xrif difference/un-difference cycle using the first image works with white noise for uint64_t.
Definition at line 442 of file xrif_test_difference_first_whitenoise.c.
References xrif_new(), and XRIF_NOERROR.